In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant", 50)

[30, 46]

In [ ]:
max_length = 4
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[45 18  0  0]
 [30 46  0  0]
 [31  5  0  0]
 [39 42 27  0]
 [21  6 27  0]
 [22 18  0  0]
 [38  6 24  0]
 [49 30  0  0]
 [49 27  0  0]
 [11 21  0  0]]


In [ ]:
model = Sequential()
embeded_vector_size = 5
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.fit(X, y, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 1.0000 - loss: 0.6145


1.0

In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [ ]:
list(weights[13])

[0.0061048046, 0.031530213, -0.019687712, -0.026519502, -0.0478629]

In [ ]:
embedding_vector = weights[13]
print(embedding_vector)

[ 0.0061048   0.03153021 -0.01968771 -0.0265195  -0.0478629 ]


In [ ]:
import tensorflow as tf
embedding_matrix = [list(weights[i]) for i in range(vocab_size)]
embedding_matrix = tf.convert_to_tensor(embedding_matrix)
# embedding_matrix = tf.Variable(embedding_matrix)  ----Or you can do like this
embedding_matrix

<tf.Tensor: shape=(50, 5), dtype=float32, numpy=
array([[-2.86706313e-02,  1.61788450e-03, -3.98673825e-02,
         2.24856958e-02,  1.63891669e-02],
       [ 2.88908146e-02,  3.04538943e-02,  2.88514830e-02,
        -1.45743378e-02, -4.58168164e-02],
       [ 4.85246889e-02,  4.51984666e-02,  6.96875155e-04,
         9.02198255e-04,  4.30475511e-02],
       [-3.44876200e-03, -3.70579138e-02, -3.21608409e-02,
         3.57946791e-02,  1.90812014e-02],
       [ 4.40371372e-02, -3.11428439e-02, -8.11667368e-03,
         4.61487882e-02, -3.53828073e-02],
       [-7.56574795e-02, -5.82732596e-02,  7.93222524e-03,
        -4.59109060e-02, -4.05674540e-02],
       [ 1.36442715e-02,  1.85660776e-02,  4.58069667e-02,
         1.30580179e-02, -2.28940696e-02],
       [ 1.47971399e-02,  4.07754444e-02, -4.12362441e-02,
         8.42060894e-03,  4.48719151e-02],
       [-1.42291188e-02, -7.08068535e-03, -3.49169970e-02,
        -4.04914021e-02,  4.85981219e-02],
       [ 2.13003866e-02,  4.80288